### PR TITLE
Bump PAT Version to 0.24.0 for release

### PR DESCRIPTION
**Pull request by dekatzenel**
### Background

Version bump to 0.24.0 for PAT release

### Changes
Release will include
* New `panther_analysis_tool validate` command (bulk upload validate)
* Now supports testing detections with a dependency on `policyuniverse`
* Improved Simple Detections support
* Support `Heroku.Runtime` LogType
* Version bump to 0.24.0 for PAT release

### Testing

* Followed release instructions including local testing

### CODE REVIEW

**Review by darwayne — APPROVED** [review]
If anyone is curious [this is what ](https://github.com/panther-labs/panther_analysis_tool/compare/v0.23.0...master)should be going into the new release

**Comment by edyesed** [comment]
@dekatzenel  can you bring the executive summary of what's in this release?

**Comment by dekatzenel** [comment]
> @dekatzenel can you bring the executive summary of what's in this release?

@edyesed added to the initial comment

**Review by edyesed — APPROVED** [review]
bumps PAT release

**Pull request merged**
