### PR TITLE
Updating schemas.py to include Auth0.Events

### PR DESCRIPTION
**Pull request by yusufak-panther**
### Background

Updating schemas.py to include Auth0.Events. This fixes the [issue](https://panther-labs.slack.com/archives/C026QGU2UG4/p1684426840916579) raised by Andy in Slack.

Closes https://app.asana.com/0/1204556313175377/1204623081932042

### Changes

* <Describe changes here>

### Testing

* <Testing steps>

### CODE REVIEW

**Review by andrea-youwakim — APPROVED** [review]
approving, please wait for someone from detections to approve before merging

**Review by andrea-youwakim — CHANGES_REQUESTED** [review]
failing test and lint, please fix first 
added reviewer from detections to ensure we got all the changes we need

**Comment by yusufak-panther** [comment]
Is the asana update check required? It seems like it should be optional given what it is. Also, it's failing even after I added a link to the asana task. Error is `Input required and not supplied: asana-pat` - seems something might be misconfigured

**Review by andrea-youwakim — COMMENTED** [review]
adding @zacbrown  to the review to bump up the version number and publish a new version of PAT

**Comment by darwayne** [comment]
Hmm let me see if closing and re-opening will fix the broken ci check 🤔

**Comment by darwayne** [comment]
this looks mostly good. let me run a few tests before we merge this in

**Comment by darwayne** [comment]
Ok this is good to go. We'll get this into a special release branch once this PR is merged in: #288

**Review by darwayne — APPROVED** [review]

**Pull request merged**
