### PR TITLE
Release 0.25.0

### PR DESCRIPTION
**Pull request by maxrichie5**
### Background

Releasing 0.25.0 

### Changes

* New Tenable Vulnerability Log Type (#334)
* Managed Field discovery (#326)
* Benchmark command (#335...#339)
* Fix various log types missing from validation (#340)

### CODE REVIEW

**Comment by edyesed** [comment]
Lines 79-82 and line 99 from #340 seem to be for lookup tables, which I think aren't strictly log types. 

Probably no harm in having them included, and I do not know whatever consequences may exist if somebody were to create a detection that had this as the input LogType.

**Review by edyesed — APPROVED** [review]

**Comment by darwayne** [comment]
hmm good call out @edyesed it is an option in the UI today. If that's wrong we should probably fix that
image

**Comment by edyesed** [comment]
> hmm good call out @edyesed it is an option in the UI today for log types. If that's wrong we should probably fix that image

I did not realize they surfaced there as well. Maybe we should check in with the Data team. If they're currently in the UI, then that is great because this brings panther_analysis_tool to parity 💪

**Comment by darwayne** [comment]
Yeah I think we're good to merge this as is. If we find out these are no bueno we can fix them in a follow up.

**Review by darwayne — APPROVED** [review]

**Pull request merged**
