### PR TITLE
Bump version to 0.22.2

### PR DESCRIPTION
**Pull request by dekatzenel**
### Background

Version bump to 0.22.2 in preparation for a release

### Changes

* <Describe changes here>

### Testing

* <Testing steps>

### CODE REVIEW

**Review by darwayne — APPROVED** [review]

**Comment by edyesed** [comment]
why would we version bump with no other code changes? What does this version change represent?

**Comment by dekatzenel** [comment]
> why would we version bump with no other code changes? What does this version change represent?

@edyesed because we previously had code changes with no version bump and now we would like to release them.
Specifically:
https://github.com/panther-labs/panther_analysis_tool/pull/291
https://github.com/panther-labs/panther_analysis_tool/pull/290
https://github.com/panther-labs/panther_analysis_tool/pull/289

**Comment by dekatzenel** [comment]
> > > why would we version bump with no other code changes? What does this version change represent?
> > 
> > 
> > @edyesed because we previously had code changes with no version bump and now we would like to release them. Specifically: #291 #290 #289
> 
> Can you provide the public release blurb for those? some of them are beefy and I'm not familiar with this codebase.

https://github.com/panther-labs/panther_analysis_tool/pull/290 - No user impact (change code owner for files)
https://github.com/panther-labs/panther_analysis_tool/pull/289 and https://github.com/panther-labs/panther_analysis_tool/pull/291 - Improved testing of to-be-released Simple Detections functionality, plus some minor refactoring
Oh and looks like we're also getting https://github.com/panther-labs/panther_analysis_tool/pull/294 - adds MongoDB.OrganizationEvent and MongoDB.ProjectEvent LogType support

**Review by edyesed — APPROVED** [review]
prep for testing of to-be-released Simple Detections functionality and support for MongoDB.OrganizationEvent and MongoDB.ProjectEvent LogTypes. Thank you!

**Pull request merged**
